%% Input: rad   Output: rad      
% All have to be rad
function BVH_Nao = NaoData_To_NaoBVH_2( NaoData, ROOT_Hips, BVHFormat,BVHHeadStr )

NaoDataName = { 'HeadYaw','HeadPitch','LShoulderPitch','LShoulderRoll','LElbowYaw'...
            'LElbowRoll','RShoulderPitch','RShoulderRoll','RElbowYaw','RElbowRoll'...
            'HipYawPitch','LHipRoll','LHipPitch','LKneePitch','RHipRoll','RHipPitch'...
            'RKneePitch','LAnklePitch','LAnkleRoll','RAnklePitch','RAnkleRoll'...
            'LWristYaw','RWristYaw','LHand','RHand'};
N = length( NaoDataName );        
for k=1:N
   eval( sprintf('%s = NaoData(k,:) ;',NaoDataName{k}) ); 
end
% dbstop in NaoData_To_NaoBVH
BVH_Nao = NaoData_To_NaoBVH(  HeadYaw, HeadPitch, LShoulderPitch, LShoulderRoll, LElbowYaw,  LElbowRoll, ...
           RShoulderPitch, RShoulderRoll, RElbowYaw , RElbowRoll, ...
           HipYawPitch, LHipRoll , LHipPitch , LKneePitch , RHipRoll , RHipPitch, ...
           RKneePitch , LAnklePitch , LAnkleRoll , RAnklePitch , RAnkleRoll, ...
           LWristYaw , RWristYaw , LHand , RHand, ROOT_Hips, BVHFormat,BVHHeadStr   ) ;

