
%% otherMakers 初始化
function otherMakers = otherMakersInitial( V_N,visualFre,Max_otherMakersN )


otherMakers_i = struct( ....
    'frequency',visualFre,....
    'Position',NaN(3,Max_otherMakersN),....
    'otherMakersN',-1, ....
     'time',NaN,'trackedMakerPosition',....
     NaN(3,1),'ContinuesFlag',....
     NaN(1,Max_otherMakersN),...
     'ContinuesLastPosition',NaN(3,Max_otherMakersN),....
     'ContinuesLastTime',NaN(1,Max_otherMakersN),...
     'ContinuesLastK',NaN(1,Max_otherMakersN),....
     'ContinuesLasti',NaN(1,Max_otherMakersN),...
     'InitialJointK',NaN(1,Max_otherMakersN)....
     );
 
otherMakers = repmat(otherMakers_i,1,V_N);
% 
% for k=1:V_N
%     otherMakers(k).frequency = visualFre;
%     otherMakers(k).Position = NaN(3,Max_otherMakersN);
%     otherMakers(k).otherMakersN = -1;
%     otherMakers(k).time = NaN;
% %     otherMakers(k).MarkerSet = 16 ;  % 'head';
%     otherMakers(k).trackedMakerPosition  = NaN(3,1);  
%     otherMakers(k).ContinuesFlag = NaN(1,Max_otherMakersN);
%     otherMakers(k).ContinuesLastPosition = NaN(3,Max_otherMakersN);
%     otherMakers(k).ContinuesLastTime = NaN(1,Max_otherMakersN);
%     otherMakers(k).ContinuesLastK = NaN(1,Max_otherMakersN);
%     otherMakers(k).ContinuesLasti = NaN(1,Max_otherMakersN);
%     
%     otherMakers(k).InitialJointK = NaN(1,Max_otherMakersN);  % 对应惯性节点序号
% end
